/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 70_mustang.glb -T 
Files: 70_mustang.glb [1.04MB] > D:\College\Project\mustang\public\models\70_mustang-transformed.glb [102.95KB] (90%)
Author: Bandit.545 (https://sketchfab.com/Bandit.545)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/70-mustang-stylized-deff1d1375764bf7ac021ddee52a74ce
Title: 70' Mustang (Stylized)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mustang_both(props) {
  const { nodes, materials } = useGLTF('/models/Mustang_both-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.S_Mustang_Color_1} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['S_Mustang_Color_1.001']} position={[2.852, 0, 0.085]} rotation={[-Math.PI, 0.436, -Math.PI]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.S_Mustang_pAL} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.S_Mustang_outline} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/models/Mustang_both-transformed.glb')
