/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mustang_boss_429.glb -T 
Files: mustang_boss_429.glb [36.24MB] > D:\College\Project\mustang\public\models\mustang_boss_429-transformed.glb [3.48MB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mustang_boss_429-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/mustang_boss_429-transformed.glb')
