/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mustang_boss_302.glb -T 
Files: mustang_boss_302.glb [67.07MB] > D:\College\Project\mustang\public\models\mustang_boss_302-transformed.glb [4.96MB] (93%)
Author: toddeppe (https://sketchfab.com/toddeppe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mustang-boss-70-0d136dcb9c1a45b3913725f49b1de2b1
Title: Mustang Boss 70
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mustang_boss_302(props) {
  const { nodes, materials } = useGLTF('/models/mustang_boss_302-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.FLOOR} scale={100} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.INTERIOR} scale={100} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.TIRE} scale={100} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.WHEEL} scale={100} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.BODY} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/mustang_boss_302-transformed.glb')
